### ISSUE TITLE
conductor server hikari pool deadlock

### ISSUE THREAD

**Issue by ghkdwlgns612** [conductor-oss/conductor#104]
**Details**
Conductor version: 3.13.6
Persistence implementation: Mysql
Queue implementation: Mysql
Lock: Zookeeper

We are using the Mysql implementation for all DAO interfaces except IndexDAO. The worker sends a polling request to the Conductor-server every one second. Currently, there are one conductor-server and seven or eight conductor-workers in use.
However, the following error occurs when Workflow and Task are not running. The reason is expected to be due to ```executionDAOFacade.updateTaskLastPoll(taskType, domain, workerId)``` inside the Polling method.

Any suggestions other than increasing the number of Conductor-servers? I'm thinking of updating only if there is a Polled Task.

```
09:05:11.982 [http-nio-8080-exec-8] ERROR com.netflix.conductor.core.dal.ExecutionDAOFacade - Error updating PollData for task: sink-worker in domain: null from worker: demo-ndap-ndap-conductor-worker-6c695bd677-ccfz8
com.netflix.conductor.core.exception.NonTransientException: (conn=20936) Lock wait timeout exceeded; try restarting transaction
	at com.netflix.conductor.mysql.dao.MySQLBaseDAO.getWithRetriedTransactions(MySQLBaseDAO.java:147) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLBaseDAO.withTransaction(MySQLBaseDAO.java:192) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLExecutionDAO.updateLastPollData(MySQLExecutionDAO.java:527) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.core.dal.ExecutionDAOFacade.updateTaskLastPoll(ExecutionDAOFacade.java:585) ~[conductor-core-7.2.0-SNAPSHOT.jar!/:7.2.0-SNAPSHOT]
	at com.netflix.conductor.service.ExecutionService.poll(ExecutionService.java:182) ~[conductor-core-7.2.0-SNAPSHOT.jar!/:7.2.0-SNAPSHOT]
	at com.netflix.conductor.service.TaskServiceImpl.batchPoll(TaskServiceImpl.java:89) ~[conductor-core-7.2.0-SNAPSHOT.jar!/:7.2.0-SNAPSHOT]
	at com.netflix.conductor.service.TaskServiceImpl$$FastClassBySpringCGLIB$$d78c3007.invoke(<generated>) ~[conductor-core-7.2.0-SNAPSHOT.jar!/:7.2.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar!/:5.3.22]
...
Caused by: com.netflix.conductor.core.exception.NonTransientException: (conn=20936) Lock wait timeout exceeded; try restarting transaction
	at com.netflix.conductor.mysql.util.Query.executeUpdate(Query.java:284) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLExecutionDAO.lambda$insertOrUpdatePollData$55(MySQLExecutionDAO.java:1008) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLBaseDAO.query(MySQLBaseDAO.java:224) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLExecutionDAO.insertOrUpdatePollData(MySQLExecutionDAO.java:1001) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLExecutionDAO.lambda$updateLastPollData$24(MySQLExecutionDAO.java:527) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLBaseDAO.lambda$withTransaction$4(MySQLBaseDAO.java:194) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]
	at com.netflix.conductor.mysql.dao.MySQLBaseDAO.getWithTransaction(MySQLBaseDAO.java:121) ~[conductor-mysql-persistence-3.13.3.jar!/:3.13.3]

```

**Comment by jeffbulltech** [comment]
👋 **Hi** @ghkdwlgns612 

We're currently reviewing open issues in the Conductor OSS backlog, and noticed that this issue hasn't been addressed. 

**To help us keep the backlog focused and actionable, we’d love your input:**  
- Is this issue still relevant?  
- Has the problem been resolved in the latest version [v3.21.12](https://github.com/conductor-oss/conductor/releases/tag/v3.21.12)?  
- Do you have any additional context or updates to provide?  

If we don’t hear back in the next **14 days**, we’ll assume this issue is no longer active and will close it for housekeeping. Of course, if it's still a valid issue, just let us know and we’ll keep it open!  

Thanks for contributing to Conductor OSS! We appreciate your support. 🙌  

### Jeff Bull
**Developer Community Manager | Orkes**

[DM on Conductor Slack](https://orkes-conductor.slack.com/team/U07NH4REXU4)
[Email me!](mailto:jeff.bull@orkes.io)
