### ISSUE TITLE
some workflow deleted automatically 

### ISSUE THREAD

**Issue by nehaMittal18Git** [conductor-oss/conductor#138]
**Describe the bug**
some workflow deleted automatically 

**Details**
Conductor version: 3.2.0
Persistence implementation: dynamite
Queue implementation: Redis queues
Lock: Redis 

**Expected behavior**
workflow should not be deleted

**Screenshots**
14:35:33.798 [http-nio-8080-exec-5] ERROR com.netflix.conductor.rest.controllers.ApplicationExceptionMapper - Error ApplicationException url: '/api/workflow/provision_sim_wf'
com.netflix.conductor.core.exception.ApplicationException: No such workflow found by name: provision_sim_wf, version: null
	at com.netflix.conductor.service.MetadataServiceImpl.lambda$getWorkflowDef$0(MetadataServiceImpl.java:133) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at com.netflix.conductor.service.MetadataServiceImpl.getWorkflowDef(MetadataServiceImpl.java:132) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.MetadataServiceImpl$$FastClassBySpringCGLIB$$726d989d.invoke(<generated>) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.MetadataServiceImpl$$EnhancerBySpringCGLIB$$9234a04b.getWorkflowDef(<generated>) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.WorkflowServiceImpl.startWorkflow(WorkflowServiceImpl.java:161) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.WorkflowServiceImpl$$FastClassBySpringCGLIB$$c01ac20d.invoke(<generated>) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.service.WorkflowServiceImpl$$EnhancerBySpringCGLIB$$6c49829b.startWorkflow(<generated>) ~[conductor-core-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at com.netflix.conductor.rest.controllers.WorkflowResource.startWorkflow(WorkflowResource.java:65) ~[conductor-rest-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor411.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]

**Comment by Richabh24** [comment]
Did anyone faced this issue . or what can be done in configuration to resolve issue?

**Comment by jeffbulltech** [comment]
👋 **Hi** @nehaMittal18Git & @Richabh24 

We're currently reviewing open issues in the Conductor OSS backlog, and noticed that this issue hasn't been addressed. 

**To help us keep the backlog focused and actionable, we’d love your input:**  
- Is this issue still relevant?  
- Has the problem been resolved in the latest version [v3.21.12](https://github.com/conductor-oss/conductor/releases/tag/v3.21.12)?  
- Do you have any additional context or updates to provide?  

If we don’t hear back in the next **14 days**, we’ll assume this issue is no longer active and will close it for housekeeping. Of course, if it's still a valid issue, just let us know and we’ll keep it open!  

Thanks for contributing to Conductor OSS! We appreciate your support. 🙌  

### Jeff Bull
**Developer Community Manager | Orkes**

[DM on Conductor Slack](https://orkes-conductor.slack.com/team/U07NH4REXU4)
[Email me!](mailto:jeff.bull@orkes.io)
