### ISSUE TITLE
S3 external storage cannot be used due to missing java dependencies

### ISSUE THREAD

**Issue by Pabosik** [conductor-oss/conductor#29]
Description:
When one tries to use an external storage for payloads (AWS S3) together with payload size thresholds as described [here](https://web.archive.org/web/20230608031205/https://conductor.netflix.com/documentation/advanced/externalpayloadstorage.html#amazon-s3), the task fails and the workflow is terminated with the following error:

```
conductor-server                  | 894377 [http-nio-8080-exec-10] ERROR com.netflix.conductor.rest.controllers.ApplicationExceptionMapper [] - Error ServletException url: '/api/tasks'
conductor-server                  | jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
conductor-server                  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-embed-websocket-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-10.1.13.jar!/:?]
conductor-server                  | 	at java.lang.Thread.run(Thread.java:840) [?:?]
conductor-server                  | Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
conductor-server                  | 	at com.amazonaws.util.Base64.encodeAsString(Base64.java:39) ~[aws-java-sdk-core-1.11.86.jar!/:?]
conductor-server                  | 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1722) ~[aws-java-sdk-s3-1.11.86.jar!/:?]
conductor-server                  | 	at com.netflix.conductor.s3.storage.S3PayloadStorage.upload(S3PayloadStorage.java:131) ~[conductor-awss3-storage-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.utils.ExternalPayloadStorageUtils.uploadHelper(ExternalPayloadStorageUtils.java:209) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.utils.ExternalPayloadStorageUtils.verifyAndUpload(ExternalPayloadStorageUtils.java:164) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.dal.ExecutionDAOFacade.externalizeTaskData(ExecutionDAOFacade.java:270) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.dal.ExecutionDAOFacade.updateTask(ExecutionDAOFacade.java:507) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:852) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:245) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.service.TaskServiceImpl.updateTask(TaskServiceImpl.java:134) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at jdk.internal.reflect.GeneratedMethodAccessor124.invoke(Unknown Source) ~[?:?]
conductor-server                  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
conductor-server                  | 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
conductor-server                  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:141) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.service.TaskServiceImpl$$SpringCGLIB$$0.updateTask(<generated>) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.rest.controllers.TaskResource.updateTask(TaskResource.java:83) ~[conductor-rest-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at jdk.internal.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
conductor-server                  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
conductor-server                  | 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
conductor-server                  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	... 43 more
conductor-server                  | Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
conductor-server                  | 	at com.amazonaws.util.Base64.encodeAsString(Base64.java:39) ~[aws-java-sdk-core-1.11.86.jar!/:?]
conductor-server                  | 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1722) ~[aws-java-sdk-s3-1.11.86.jar!/:?]
conductor-server                  | 	at com.netflix.conductor.s3.storage.S3PayloadStorage.upload(S3PayloadStorage.java:131) ~[conductor-awss3-storage-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.utils.ExternalPayloadStorageUtils.uploadHelper(ExternalPayloadStorageUtils.java:209) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.utils.ExternalPayloadStorageUtils.verifyAndUpload(ExternalPayloadStorageUtils.java:164) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.dal.ExecutionDAOFacade.externalizeTaskData(ExecutionDAOFacade.java:270) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.dal.ExecutionDAOFacade.updateTask(ExecutionDAOFacade.java:507) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.core.execution.WorkflowExecutor.updateTask(WorkflowExecutor.java:852) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.service.ExecutionService.updateTask(ExecutionService.java:245) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.service.TaskServiceImpl.updateTask(TaskServiceImpl.java:134) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at jdk.internal.reflect.GeneratedMethodAccessor124.invoke(Unknown Source) ~[?:?]
conductor-server                  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
conductor-server                  | 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
conductor-server                  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:141) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.service.TaskServiceImpl$$SpringCGLIB$$0.updateTask(<generated>) ~[conductor-core-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at com.netflix.conductor.rest.controllers.TaskResource.updateTask(TaskResource.java:83) ~[conductor-rest-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
conductor-server                  | 	at jdk.internal.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
conductor-server                  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
conductor-server                  | 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
conductor-server                  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) [spring-webmvc-6.0.12.jar!/:6.0.12]
conductor-server                  | 	... 43 more
```

**Solution**

The issue can be fixed by adding the following lines inside build.gradle:

```
    dependencies {
        ...
        implementation('javax.xml.bind:jaxb-api:2.3.1')
        implementation('com.sun.xml.bind:jaxb-core:2.3.0.1')
        implementation('com.sun.xml.bind:jaxb-impl:2.3.3')
        ...
    }
```

The issue is related to the version of java and which dependencies are contained on the default classpath. Here is a related [topic on SO](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception). 

After adding the aforementioned lines and restarting conductor, S3 as external storage works normally.

Why didn't I submit a PR, when I have the solution? Because I am not a Java developer and I would very much appreciate if someone more experienced took a look at this and implemented a proper solution. Mine works, but maybe it's not entirely correct... I just don't know.

**Details**
Conductor version: v3.15.0
Persistence implementation: Redis
Queue implementation: Redis
Lock: Redis
Workflow definition: -
Task definition: -
Event handler definition: -

**To Reproduce**
1. Clone repo from main branch and latest
2. Deploy conductor locally using docker compose build. Note that some changes must be made to the docker-compose and config-redis.properties in order for this to work.

Docker-compose.yaml changes - add the following env vars to conductor-server:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_REGION

config-redis.properties changes - setup S3 as external storage, add these params:
  
  - conductor.external-payload-storage.type=s3
  - conductor.external-payload-storage.s3.bucketName=YOUR BUCKET NAME HERE
  - conductor.external-payload-storage.s3.region=YOUR AWS REGION HERE
  - conductor.app.workflowInputPayloadSizeThreshold=5120
  - conductor.app.maxWorkflowInputPayloadSizeThreshold=10240
  - conductor.app.workflowOutputPayloadSizeThreshold=100
  - conductor.app.maxWorkflowOutputPayloadSizeThreshold=1024
  - conductor.app.taskInputPayloadSizeThreshold=3072
  - conductor.app.maxTaskInputPayloadSizeThreshold=10240
  - conductor.app.taskOutputPayloadSizeThreshold=100
  - conductor.app.maxTaskOutputPayloadSizeThreshold=1024

3. You need to create a dummy worker that creates an output larger than conductor.app.taskOutputPayloadSizeThreshold (the value is in KB).
4. Create a workflow that uses the worker from step 3.
5. Execute workflow
6. See error.

**Expected behavior**
Upload payload to S3 if bigger than threshold.

Thank you in advance!

**Comment by jeffbulltech** [comment]
👋 **Hi** @Pabosik 

We're currently reviewing open issues in the Conductor OSS backlog, and noticed that this issue hasn't been addressed. 

**To help us keep the backlog focused and actionable, we’d love your input:**  
- Is this issue still relevant?  
- Has the problem been resolved in the latest version [v3.21.12](https://github.com/conductor-oss/conductor/releases/tag/v3.21.12)?  
- Do you have any additional context or updates to provide?  

If we don’t hear back in the next **14 days**, we’ll assume this issue is no longer active and will close it for housekeeping. Of course, if it's still a valid issue, just let us know and we’ll keep it open!  

Thanks for contributing to Conductor OSS! We appreciate your support. 🙌  

### Jeff Bull
**Developer Community Manager | Orkes**

[DM on Conductor Slack](https://orkes-conductor.slack.com/team/U07NH4REXU4)
[Email me!](mailto:jeff.bull@orkes.io)
