### ISSUE TITLE
conductor oss docker-compose up throw ClassNotFoundException

### ISSUE THREAD

**Issue by dingliu1** [conductor-oss/conductor#30]
**Describe the bug**
conductor oss, when build and startup with docker-compose, throw ClassNotFoundException
**Details**
Conductor version:  latest
Persistence implementation: Cassandra, Postgres, MySQL, Dynomite etc -  Postgres
Queue implementation: Postgres, MySQL, Dynoqueues etc
Lock: Redis or Zookeeper?
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**
1. git clone https://github.com/conductor-oss/conductor.git
2. go to docker folder
3. docker-compose -f docker-compose-postgres-es7.yaml build
4. docker-compose -f docker-compose-postgres-es7.yaml up
5. When conductor server starts up it reports below error:

conductor-server                  |     at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
conductor-server                  |     at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[conductor-es7-persistence-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
conductor-server                  |     ... 27 more
conductor-server                  | Caused by: java.lang.ClassNotFoundException: javax.validation.Validator
conductor-server                  |     at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
conductor-server                  |     at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
conductor-server                  |     at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149) ~[conductor-server.jar:0.1.0-SNAPSHOT]
conductor-server                  |     at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
conductor-server                  |     at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
conductor-server                  |     at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
conductor-server                  |     at java.lang.Class.getDeclaredConstructors(Class.java:2555) ~[?:?]

**Expected behavior**
docker-compose up should not report any error

**Screenshots**

**Additional context**

**Comment by dingliu1** [comment]
Sorry, verified again this is not a issue
