### ISSUE TITLE
Error when creating a workflow with ES7

### ISSUE THREAD

**Issue by JCHacking** [conductor-oss/conductor#37]
**Describe the bug**
When I try to create a workflow I get this error:
```
2024-01-03 11:34:05.349 ERROR 1 --- [led-task-pool-3] c.n.c.c.r.WorkflowReconciler : Error when polling for workflows
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/elasticsearch/common/xcontent/XContentType
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
at com.netflix.conductor.core.reconciliation.WorkflowReconciler.pollAndSweep(WorkflowReconciler.java:77) ~[conductor-core-3.15.0.jar!/:3.15.0]
at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[conductor-es7-persistence-3.16.0-SNAPSHOT.jar!/:3.16.0-SNAPSHOT]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Details**
Conductor version: 3.15.0
Persistence implementation: MySQL
Lock: None

**Expected behavior**
Fix to be able to use condutor 3.15.0 with ES7

**Comment by v1r3n** [comment]
Hi @JCHacking can you try with the latest release?

**Comment by JCHacking** [comment]
Hi @v1r3n 
I managed to solve it, I think the problem was that the build was done with an alpine image and therefore did not add well that library.
